"""UI configuration defaults for the Gradio frontend."""

APP_TITLE = "Information Retrieval System"
APP_SUBTITLE = "Search, retrieve, augment, evaluate"
APP_THEME_CSS = "styles/theme.css"

# Search
DEFAULT_MAX_LOCAL_RESULTS = 5
DEFAULT_MAX_WEB_RESULTS = 10
DEFAULT_MIN_DOCUMENTS = 500
DEFAULT_ENABLE_WEB_SEARCH = True
DEFAULT_AUTO_RELOAD = True
DEFAULT_QUERY_MIN_LENGTH = 3
DEFAULT_QUERY_MAX_LENGTH = 1000

# LLM
DEFAULT_OLLAMA_MODEL = "ollama3.2:latest"
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434"
DEFAULT_RAG_TEMPLATE = "domain_specific"
DEFAULT_OLLAMA_TIMEOUT = 300
DEFAULT_RAG_TEMPERATURE = 0.7
DEFAULT_RAG_MAX_TOKENS = 1024
DEFAULT_MAX_CITES = 10
DEFAULT_MAX_CONTEXT_DOC_LENGTH = 1000

# Crawlers
DEFAULT_MAX_ARTICLES_PER_SPIDER = 1000
DEFAULT_FORCE_RECRAWL = False

# DB
DEFAULT_USE_INITIAL_CORPUS = True
DEFAULT_CLEAR_RAW = True # When clearing DB
